### ISSUE TITLE
Avoid flashing stand when player sits

### ISSUE THREAD

**Issue by VicenteRD** [RifleDLuffy/RFChairs#3]
When you sit down, due to client delay and how the logic is, the player sees the stand before actually sitting down, or while being sat down. To improve this, you can use the `World` method that allows you to provide a `Consumer` that turns the stand invisible before putting it into the world. This would replace the spawning in line 263 of `Util` (https://github.com/RifleDLuffy/RFChairs/blob/master/src/com/rifledluffy/chairs/utility/Util.java#L263), looking something like this:

	ArmorStand armorStand = (ArmorStand) seat.getWorld().spawn(
		seat.add(0.5, height, 0.5).setDirection(vector),
		ArmorStand.class,
		stand -> {
			stand.setVisible(false);
			stand.setGravity(false);
			stand.setInvulnerable(true);
			stand.setMarker(true);
			stand.setCollidable(false);
		});

**Comment by ShinyDeagle** [comment]
Splendid!

I've been looking for a solution for this for quite a while now.

You'll have to excuse my slow response time.

I'm currently settling in my new apartment so when I get some free time. I'll test this out and, if it works, push it to the next patch.

Thank you!

**Comment by VicenteRD** [comment]
You're welcome! I was too lazy to do what Carl did, but I can assure you it does the trick :D 
And take your time, no worries ^^

**Comment by ShinyDeagle** [comment]
I put both your names in plugin.yml, if you want me to change it. Let me know here

**Comment by carlpoole** [comment]
Thats nice of you, thanks
